---
title: "Data Import"
output: github_document
---

This file is for doing data import.

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Import our first dataset.

```{r}
litters_df =
  read_csv(
    file = "data/FAS_litters.csv",
    na = c("", "NA", ".")
    )

litters_df = janitor::clean_names(litters_df)
```

Import our second dataset.

```{r}
pups_df = 
  read_csv(
    file = "data/FAS_pups.csv",
    na = c("", "NA", "."),
    skip = 3
    )

pups_df = janitor::clean_names(pups_df)
```

## Look at the data

```{r}
litters_df
pups_df
```

Head or tail

```{r}
head(litters_df, 20)

tail(pups_df, 5)
```

Skim

```{r}
skimr::skim(pups_df)
```

## Import Excel

Load MLB data

```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

Look at MLB data

```{r}
mlb_df
```

Load LoTR data

```{r}
fotr_df =
  read_excel(
    "data/LoTR_Words.xlsx", 
    range = "B3:D6"
  )

fotr_df
```

```{r}
tt_df =
  read_excel(
    "data/LoTR_Words.xlsx", 
    range = "F3:H6"
  )

tt_df
```

## Import SAS

Read PULSE dataset

```{r}
pulse_df =
  read_sas("data/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
```

