---
title: "Tidy Data"
output: github_document
---

This file is for doing data tidying.

```{r}
library(tidyverse)
```

## Let's tidy data

```{r, eval = FALSE}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()
```

`bdi_score` is spread across multiple columns.

```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi_score"
  ) |>
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  )
```

Import the litters data, keep columns litter number and GD weights, and tidy.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("", "NA", ".")) |>
  janitor::clean_names() |>
  select(litter_number, gd0_weight, gd18_weight) |>
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight"
  ) |>
  mutate(
    gd = case_match(
      gd,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )
```

## Deliberately untidy data

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean_outcome = c(4.0, 8.0, 3.5, 4.0)
  )
```

Let's untidy for human readability.

```{r}
analysis_df |>
  pivot_wider(
    names_from = time,
    values_from = mean_outcome
  ) |>
  knitr::kable()
```


